### ISSUE TITLE
Alternate Storage Folder

### ISSUE THREAD

**Issue by GrandpaDK** [tzutalin/DriveRecorder#10]
I am able to select the alternate storage location in "storage options" which changes it to my SD card but it buries it deep within the Android folder.  Is there a way to select which folder is used for this storage on the SD card.

**Comment by tzutalin** [comment]
Hi @GrandpaDK ,
Currently, it is unable to support that. Due to Android policy, the folder of this app should be located at the top folder of sdcard.
