### ISSUE TITLE
The app closes immediately

### ISSUE THREAD

**Issue by ghost** [tzutalin/DriveRecorder#12]
Hello, I installed Driver Recorder on a Samsung Galaxy Tab A7 Lite tablet, model name SM-T220 every time I click on the icon the dash cam opens but immediately shuts down, how can I do to solve the problem? Thank you .

**Comment by tzutalin** [comment]
Hi sorry to hear that. Does it happen recently since we just release the newer version?
What is the app version?
Does it crash when opening the app or crash when clicking record?

**Comment by ghost** [comment]
Hello I have the latest version of the app, that of March 26, 2023, when I click on the icon opens but immediately closes, can not record even for a second

Inviato da Proton Mail mobile

-------- Messaggio originale --------
Il 4 Apr 2023, 23:54, darrenl ha scritto:

**Comment by tzutalin** [comment]
Thanks for letting me know. Got the issue. Going to fix it in an hour

**Comment by tzutalin** [comment]
The release is imminent and should be accessible on Google Play in the next three hours. Please inform me if you encounter any problems with it. thanks

**Comment by ghost** [comment]
Hello, I made the update and I must say that now it works well, so the ticket can be closed, thank you very much.

Inviato da Proton Mail mobile

-------- Messaggio originale --------
Il 5 Apr 2023, 03:15, darrenl ha scritto:

**Comment by tzutalin** [comment]
Hi thanks. Have a good day

**Comment by ghost** [comment]
good morning, the application works well, but I would like to know if it is possible to change the video screen, there is difficulty reading the date of the video, thank you very much.

Inviato da Proton Mail mobile

-------- Messaggio originale --------
Il 5 Apr 2023, 18:29, darrenl < ***@***.***> ha scritto:
Hi thanks. Have a good day
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.￼Message ID: ***@***.***>
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[https://github.com](<a href=)/tzutalin/DriveRecorder/issues/12#issuecomment-1497786286">https://github.com/tzutalin/DriveRecorder/issues/12#issuecomment-1497786286", "url": "[https://github.com](<a href=)/tzutalin/DriveRecorder/issues/12#issuecomment-1497786286">https://github.com/tzutalin/DriveRecorder/issues/12#issuecomment-1497786286", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by ghost** [comment]
I sent you a screenshot

Inviato da Proton Mail mobile

-------- Messaggio originale --------
Il 5 Apr 2023, 18:29, darrenl < ***@***.***> ha scritto:
Hi thanks. Have a good day
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.￼Message ID: ***@***.***>
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[https://github.com](<a href=)/tzutalin/DriveRecorder/issues/12#issuecomment-1497786286">https://github.com/tzutalin/DriveRecorder/issues/12#issuecomment-1497786286", "url": "[https://github.com](<a href=)/tzutalin/DriveRecorder/issues/12#issuecomment-1497786286">https://github.com/tzutalin/DriveRecorder/issues/12#issuecomment-1497786286", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by tzutalin** [comment]
Hi there ,
Did you send the screenshot? I am into to learn more about ‘ difficulty reading the date of the video’.

**Comment by ghost** [comment]
Hi, I sent the screen, to show you that the video covers almost the entire screen, the letters are barely seen, can't the video be reduced a bit in the presentation? This makes it easier to read the dates. Thank you.

Inviato da Proton Mail mobile

-------- Messaggio originale --------
Il 11 Apr 2023, 02:31, darrenl < ***@***.***> ha scritto:
Hi there ,
Did you send the screenshot? I am into to learn more about ‘ difficulty reading the date of the video’.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.￼Message ID: ***@***.***>
[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[https://github.com](<a href=)/tzutalin/DriveRecorder/issues/12#issuecomment-1502517177">https://github.com/tzutalin/DriveRecorder/issues/12#issuecomment-1502517177", "url": "[https://github.com](<a href=)/tzutalin/DriveRecorder/issues/12#issuecomment-1502517177">https://github.com/tzutalin/DriveRecorder/issues/12#issuecomment-1502517177", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by tzutalin** [comment]
Hi @keplerkep ,
Thanks for reporting. I haven't received the screenshot. Did you send by the email?

**Comment by ghost** [comment]
Hello yes I sent you the screen via email, now with this email I sent you another Screenshot

Inviato da Proton Mail mobile

-------- Messaggio originale --------
Il 14 Apr 2023, 04:22, darrenl ha scritto:
