### ISSUE TITLE
Video Storage location

### ISSUE THREAD

**Issue by ozy1ozy** [tzutalin/DriveRecorder#3]
The App does not seem to have the option to use extended memory cards to store video.

**Comment by tzutalin** [comment]
Actually, it has.  You can go to the settings to find that option

**Comment by ozy1ozy** [comment]
[Image]


This is what it shows. I can't see any of my extended memory being selectable?


________________________________

**Comment by tzutalin** [comment]
Do you know your phone model? It might be due to your model and sd card

**Comment by ozy1ozy** [comment]
Hi Darren,

Phone’s a Huawei P smart with 32Gb of Lexar memory. The problem is, that it is not simple to work out which memory is being used due to the way your program records the memory. ☹ But I guess, no Biggy.
The manual / auto exposure is a bit off. I have to switch to manual and that is a bit limiting. It’s too dark on auto.
More of a problem is that the autofocus cannot be overridden, so a lot of focussing on the car windscreen rather than the road.
Anyway, apart from that it is a very good, simple program – well done.
NB: I find the lighting control slider a bit non-sensitive.

Regards,

Nicholas Wade

Tel: 01256892438
Mob: 07921435063

________________________________
