### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by stonecrusher** [tzutalin/DriveRecorder#4]
Is there a possibility to improve the german translation?
Some items have really bad autotranslation or are not translated at all.

**Comment by tzutalin** [comment]
Sure. Could you give a specific example?

**Comment by stonecrusher** [comment]
Error messages:
```
GPS is unavailable
Enable your GPS provider
ja
```

```
Warnung
Unable to open camera
ja
```

- Untranslated
- Instead of "ok" there's a "ja" button

---------

`Füge das Video zu einem Lieblingsvideo hinzu`
Should be `Füge das Video zu den Favoriten hinzu`

`Click to check the video and details or long-press to delete or share it`
untranslated

`Suche Videos von Zeit oder Adresse` should be `Suche Videos nach Zeit oder Ort`

----------

Main menu: `Path trajectory`
untranslated

-----------

Settings:
`Speichergröße` subtitle should be `Maximale Speicherbelegung festlegen`

`Lagermöglichkeit` should be `Speicherort` with no subtitle or `Speicherort auswählen`

`Preise aktualisieren` makes no sense but I need more info what it does to be able to translate it. If it's just the update rate of GPS then the available options make no sense. 
I think it probably should be "GPS Update-Rate" with no subtitle and available options "Hoch, Mittel, Niedrig"

```
Record as open this app
Start recording after opening this app
```
untranslated

```
Sperrbildschirm in Landschaft
Sperren Sie Ihr Gerät in Landschaft, bei der Aufnahme
```
Not sure what exactly it does. Clearly "in Landschaft" is wrong here. It should be something like "Sperrbildschirm bei Breitbild"

```
Close advertisements
Do not show pop-up ads
```
untranslated

Einheitensystem:
`Metric` --> `Metrisch`

------------

If you need help, let me know. I didn't translate everything on the run because I need to be sure what the meaning is and use a consistent glossary. Furthermore I have no idea about best practice in translation, I'm just a native german speaker.

/edit
There's more.
Like `Rotieren` should be `Drehen`

`Ausgabe ein Video mit Zeitstempel` not clear what that means

And there was another intro bubble with bad text which I can't reproduce right now

Video details are also untranslated.
`Title` --> `Titel`
`Path` --> `Speicherpfad`
`Mime type` --> `Mime Typ`
`Duration` --> `Dauer`
`Width` --> `Breite`
`Height` --> `Höhe`
`Record audio` --> `Ton aufnehmen`
`yes` --> `ja`
`no` --> `nein`
`Rotation` --> `Drehwinkel`

hope it helps so far. Thanks!

**Comment by tzutalin** [comment]
This is awesome! Will update it accordingly.

**Comment by tzutalin** [comment]
Hi @stonecrusher ,
Thanks for your help. If you don't mind, could you send me(tzu.ta.lin@gmail.com) your email. We can chat then I would like to buy you a coffee?

**Comment by stonecrusher** [comment]
Just sent you an email.
