### ISSUE TITLE
Closing when in background

### ISSUE THREAD

**Issue by moltra** [tzutalin/DriveRecorder#7]
What is the best way to close the app when it is operating in the background.  I have to open recent apps and swipe up to close.

**Comment by tzutalin** [comment]
Hi,
You can check this screenshot
https://github.com/tzutalin/DriveRecorder/blob/master/faq/faq.md#how-to-stop-the-recording-in-the-background-easily

**Comment by moltra** [comment]
Sorry, I need to research better next time.
