### ISSUE TITLE
Background close not working properly

### ISSUE THREAD

**Issue by moltra** [tzutalin/DriveRecorder#8]
S21 Ultra system info included in attached image.  
![Screenshot_20210517-080449_CPU-Z](https://user-images.githubusercontent.com/1578492/118485644-ae6c5280-b6e6-11eb-8545-1a896ceb7550.jpg)

Drive recorder 1.10.16

When the app is running in the background, when I try to stop the app by dragging the indicator to the stop circle, the app gives indications of closing, the "recording" notification goes away from the notification bar and the notification area.

A little while later the recording notification in the notification area returns and sometimes the notification bar recording icon returns.

If you need anything else let me know.

**Comment by tzutalin** [comment]
Hi there,
Does the issue still happen?
