### ISSUE TITLE
Can't use all of my micro SD card

### ISSUE THREAD

**Issue by RedDog1969** [tzutalin/DriveRecorder#9]
I installed a fresh brand new 128GB Micro SD card and formatted it. When I go into the drive recorder settings and select the Micro SD card as the storage location and 128GB as the storage size it tells me that I can't use that location with that size because the Micro SD card only has 125GB free, because of course some of the space gets used up in the format. So I have to go down to the next lower size which is 64GB. So half of my Micro SD card is wasted, not being used and taken advantage of.

**Comment by tzutalin** [comment]
Hi there, 
I understand your use case and concern. The current design is allowing 32, 64 and 128g.

if you can customize it, do you think it will be helpful?

**Comment by RedDog1969** [comment]
Yes, I think that being able to customize the data store size would be
very helpful.

**Comment by tzutalin** [comment]
Hi there,
Customizing might take longer in the UI. For now, I add another option for 96gb for you in the setting. I will release it soon.

**Comment by RedDog1969** [comment]
Thank you for your response. That is certainly a step in the right
direction. Thank you for your attention on this. Other than this issue for
me, your app is amazing!

Mike
